# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resourcemodule/resourcemodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("resourcemodule/resourcemodule.proto", :syntax => :proto3) do
    add_message "resourcemodule.BooleanControlGGIO" do
      optional :logicalNode, :message, 1, "commonmodule.LogicalNode"
      optional :Phase, :message, 2, "commonmodule.Optional_PhaseCodeKind"
      optional :SPCSO, :message, 3, "commonmodule.ControlSPC"
    end
    add_message "resourcemodule.IntegerControlGGIO" do
      optional :logicalNode, :message, 1, "commonmodule.LogicalNode"
      optional :ISCSO, :message, 2, "commonmodule.ControlINC"
      optional :Phase, :message, 3, "commonmodule.Optional_PhaseCodeKind"
    end
    add_message "resourcemodule.StringControlGGIO" do
      optional :logicalNode, :message, 1, "commonmodule.LogicalNode"
      optional :Phase, :message, 2, "commonmodule.Optional_PhaseCodeKind"
      optional :StrOut, :message, 3, "commonmodule.VSC"
    end
    add_message "resourcemodule.AnalogControlGGIO" do
      optional :logicalNode, :message, 1, "commonmodule.LogicalNode"
      optional :AnOut, :message, 2, "commonmodule.ControlAPC"
      optional :Phase, :message, 3, "commonmodule.Optional_PhaseCodeKind"
    end
    add_message "resourcemodule.ResourceDiscreteControl" do
      optional :identifiedObject, :message, 1, "commonmodule.IdentifiedObject"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      repeated :analogControlGGIO, :message, 3, "resourcemodule.AnalogControlGGIO"
      repeated :booleanControlGGIO, :message, 4, "resourcemodule.BooleanControlGGIO"
      repeated :integerControlGGIO, :message, 5, "resourcemodule.IntegerControlGGIO"
      repeated :stringControlGGIO, :message, 6, "resourcemodule.StringControlGGIO"
    end
    add_message "resourcemodule.ResourceDiscreteControlProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :conductingEquipment, :message, 2, "commonmodule.ConductingEquipment"
      optional :resourceDiscreteControl, :message, 3, "resourcemodule.ResourceDiscreteControl"
    end
    add_message "resourcemodule.ResourceReading" do
      optional :conductingEquipmentTerminalReading, :message, 1, "commonmodule.ConductingEquipmentTerminalReading"
      optional :phaseMMTN, :message, 2, "commonmodule.PhaseMMTN"
      optional :readingMMTR, :message, 3, "commonmodule.ReadingMMTR"
      optional :readingMMXU, :message, 4, "commonmodule.ReadingMMXU"
    end
    add_message "resourcemodule.ResourceReadingProfile" do
      optional :readingMessageInfo, :message, 1, "commonmodule.ReadingMessageInfo"
      optional :conductingEquipment, :message, 2, "commonmodule.ConductingEquipment"
      optional :resourceReading, :message, 3, "resourcemodule.ResourceReading"
    end
    add_message "resourcemodule.ResourceEvent" do
      optional :identifiedObject, :message, 1, "commonmodule.IdentifiedObject"
      repeated :analogEventAndStatusGGIO, :message, 2, "commonmodule.AnalogEventAndStatusGGIO"
      repeated :booleanEventAndStatusGGIO, :message, 3, "commonmodule.BooleanEventAndStatusGGIO"
      repeated :integerEventAndStatusGGIO, :message, 4, "commonmodule.IntegerEventAndStatusGGIO"
      repeated :stringEventAndStatusGGIO, :message, 5, "commonmodule.StringEventAndStatusGGIO"
    end
    add_message "resourcemodule.ResourceEventProfile" do
      optional :eventMessageInfo, :message, 1, "commonmodule.EventMessageInfo"
      optional :conductingEquipment, :message, 2, "commonmodule.ConductingEquipment"
      optional :resourceEvent, :message, 3, "resourcemodule.ResourceEvent"
    end
    add_message "resourcemodule.ResourceStatus" do
      optional :identifiedObject, :message, 1, "commonmodule.IdentifiedObject"
      repeated :analogEventAndStatusGGIO, :message, 2, "commonmodule.AnalogEventAndStatusGGIO"
      repeated :booleanEventAndStatusGGIO, :message, 3, "commonmodule.BooleanEventAndStatusGGIO"
      repeated :integerEventAndStatusGGIO, :message, 4, "commonmodule.IntegerEventAndStatusGGIO"
      repeated :stringEventAndStatusGGIO, :message, 5, "commonmodule.StringEventAndStatusGGIO"
    end
    add_message "resourcemodule.ResourceStatusProfile" do
      optional :statusMessageInfo, :message, 1, "commonmodule.StatusMessageInfo"
      optional :conductingEquipment, :message, 2, "commonmodule.ConductingEquipment"
      optional :resourceStatus, :message, 3, "resourcemodule.ResourceStatus"
    end
  end
end

module Resourcemodule
  BooleanControlGGIO = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.BooleanControlGGIO").msgclass
  IntegerControlGGIO = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.IntegerControlGGIO").msgclass
  StringControlGGIO = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.StringControlGGIO").msgclass
  AnalogControlGGIO = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.AnalogControlGGIO").msgclass
  ResourceDiscreteControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.ResourceDiscreteControl").msgclass
  ResourceDiscreteControlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.ResourceDiscreteControlProfile").msgclass
  ResourceReading = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.ResourceReading").msgclass
  ResourceReadingProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.ResourceReadingProfile").msgclass
  ResourceEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.ResourceEvent").msgclass
  ResourceEventProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.ResourceEventProfile").msgclass
  ResourceStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.ResourceStatus").msgclass
  ResourceStatusProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resourcemodule.ResourceStatusProfile").msgclass
end
