# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generationmodule/generationmodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'google/protobuf/wrappers_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("generationmodule/generationmodule.proto", :syntax => :proto3) do
    add_message "generationmodule.GeneratingUnit" do
      optional :conductingEquipment, :message, 1, "commonmodule.ConductingEquipment"
      optional :maxOperatingP, :message, 2, "commonmodule.ActivePower"
    end
    add_message "generationmodule.GenerationCapabilityConfiguration" do
      optional :sourceCapabilityConfiguration, :message, 1, "commonmodule.SourceCapabilityConfiguration"
    end
    add_message "generationmodule.GenerationCapabilityOverride" do
      optional :identifiedObject, :message, 1, "commonmodule.IdentifiedObject"
      optional :generationCapabilityConfiguration, :message, 2, "generationmodule.GenerationCapabilityConfiguration"
    end
    add_message "generationmodule.GenerationCapabilityOverrideProfile" do
      optional :capabilityMessageInfo, :message, 1, "commonmodule.CapabilityMessageInfo"
      optional :generationCapabilityOverride, :message, 2, "generationmodule.GenerationCapabilityOverride"
      optional :generatingUnit, :message, 3, "generationmodule.GeneratingUnit"
    end
    add_message "generationmodule.GenerationCapabilityRatings" do
      optional :sourceCapabilityRatings, :message, 1, "commonmodule.SourceCapabilityRatings"
    end
    add_message "generationmodule.GenerationCapability" do
      optional :nameplateValue, :message, 1, "commonmodule.NameplateValue"
      optional :generationCapabilityRatings, :message, 2, "generationmodule.GenerationCapabilityRatings"
      optional :generationCapabilityConfiguration, :message, 3, "generationmodule.GenerationCapabilityConfiguration"
    end
    add_message "generationmodule.GenerationCapabilityProfile" do
      optional :capabilityMessageInfo, :message, 1, "commonmodule.CapabilityMessageInfo"
      optional :generationCapability, :message, 2, "generationmodule.GenerationCapability"
      optional :generatingUnit, :message, 3, "generationmodule.GeneratingUnit"
    end
    add_message "generationmodule.GenerationPoint" do
      optional :blackStartEnabled, :message, 1, "commonmodule.ControlSPC"
      optional :frequencySetPointEnabled, :message, 2, "commonmodule.ControlSPC"
      optional :pctHzDroop, :message, 3, "google.protobuf.FloatValue"
      optional :pctVDroop, :message, 4, "google.protobuf.FloatValue"
      optional :rampRates, :message, 5, "commonmodule.RampRate"
      optional :reactivePwrSetPointEnabled, :message, 6, "commonmodule.ControlSPC"
      optional :realPwrSetPointEnabled, :message, 7, "commonmodule.ControlSPC"
      optional :reset, :message, 8, "commonmodule.ControlSPC"
      optional :state, :message, 9, "commonmodule.Optional_StateKind"
      optional :syncBackToGrid, :message, 10, "commonmodule.ControlSPC"
      optional :transToIslndOnGridLossEnabled, :message, 11, "commonmodule.ControlSPC"
      optional :voltageSetPointEnabled, :message, 12, "commonmodule.ControlSPC"
      optional :startTime, :message, 13, "commonmodule.ControlTimestamp"
      optional :enterServiceOperation, :message, 14, "commonmodule.EnterServiceAPC"
      optional :hzWOperation, :message, 15, "commonmodule.HzWAPC"
      optional :limitWOperation, :message, 16, "commonmodule.LimitWAPC"
      optional :pFOperation, :message, 17, "commonmodule.PFSPC"
      optional :tmHzTripOperation, :message, 18, "commonmodule.TmHzCSG"
      optional :tmVoltTripOperation, :message, 19, "commonmodule.TmVoltCSG"
      optional :vArOperation, :message, 20, "commonmodule.VarSPC"
      optional :voltVarOperation, :message, 21, "commonmodule.VoltVarCSG"
      optional :voltWOperation, :message, 22, "commonmodule.VoltWCSG"
      optional :wVarOperation, :message, 23, "commonmodule.WVarCSG"
    end
    add_message "generationmodule.GenerationCSG" do
      repeated :crvPts, :message, 1, "generationmodule.GenerationPoint"
    end
    add_message "generationmodule.GenerationControlScheduleFSCH" do
      optional :ValDCSG, :message, 1, "generationmodule.GenerationCSG"
    end
    add_message "generationmodule.GenerationControlFSCC" do
      optional :controlFSCC, :message, 1, "commonmodule.ControlFSCC"
      optional :GenerationControlScheduleFSCH, :message, 2, "generationmodule.GenerationControlScheduleFSCH"
    end
    add_message "generationmodule.GenerationControl" do
      optional :controlValue, :message, 1, "commonmodule.ControlValue"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      optional :generationControlFSCC, :message, 3, "generationmodule.GenerationControlFSCC"
    end
    add_message "generationmodule.GenerationControlProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :generatingUnit, :message, 2, "generationmodule.GeneratingUnit"
      optional :generationControl, :message, 3, "generationmodule.GenerationControl"
    end
    add_message "generationmodule.DroopParameter" do
      optional :slope, :message, 1, "google.protobuf.FloatValue"
      optional :unloadedOffset, :message, 2, "google.protobuf.FloatValue"
    end
    add_message "generationmodule.RealPowerControl" do
      optional :droopSetpoint, :message, 1, "generationmodule.DroopParameter"
      optional :isochronousSetpoint, :message, 2, "google.protobuf.FloatValue"
      optional :realPowerControlMode, :message, 3, "commonmodule.Optional_RealPowerControlKind"
      optional :realPowerSetpoint, :message, 4, "google.protobuf.FloatValue"
    end
    add_message "generationmodule.ReactivePowerControl" do
      optional :droopSetpoint, :message, 1, "generationmodule.DroopParameter"
      optional :powerFactorSetpoint, :message, 2, "google.protobuf.FloatValue"
      optional :reactivePowerControlMode, :message, 3, "commonmodule.Optional_ReactivePowerControlKind"
      optional :reactivePowerSetpoint, :message, 4, "google.protobuf.FloatValue"
      optional :voltageSetpoint, :message, 5, "google.protobuf.FloatValue"
    end
    add_message "generationmodule.GenerationDiscreteControl" do
      optional :controlValue, :message, 1, "commonmodule.ControlValue"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      optional :ReactivePowerControl, :message, 3, "generationmodule.ReactivePowerControl"
      optional :RealPowerControl, :message, 4, "generationmodule.RealPowerControl"
    end
    add_message "generationmodule.GenerationDiscreteControlProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :generatingUnit, :message, 2, "generationmodule.GeneratingUnit"
      optional :generationDiscreteControl, :message, 3, "generationmodule.GenerationDiscreteControl"
    end
    add_message "generationmodule.GenerationReading" do
      optional :conductingEquipmentTerminalReading, :message, 1, "commonmodule.ConductingEquipmentTerminalReading"
      optional :phaseMMTN, :message, 2, "commonmodule.PhaseMMTN"
      optional :readingMMTR, :message, 3, "commonmodule.ReadingMMTR"
      optional :readingMMXU, :message, 4, "commonmodule.ReadingMMXU"
    end
    add_message "generationmodule.GenerationReadingProfile" do
      optional :readingMessageInfo, :message, 1, "commonmodule.ReadingMessageInfo"
      optional :generatingUnit, :message, 2, "generationmodule.GeneratingUnit"
      optional :generationReading, :message, 3, "generationmodule.GenerationReading"
    end
    add_message "generationmodule.GenerationPointStatus" do
      optional :blackStartEnabled, :message, 1, "commonmodule.StatusSPS"
      optional :frequencySetPointEnabled, :message, 2, "commonmodule.StatusSPS"
      optional :pctHzDroop, :message, 3, "google.protobuf.FloatValue"
      optional :pctVDroop, :message, 4, "google.protobuf.FloatValue"
      optional :rampRates, :message, 5, "commonmodule.RampRate"
      optional :reactivePwrSetPointEnabled, :message, 6, "commonmodule.StatusSPS"
      optional :realPwrSetPointEnabled, :message, 7, "commonmodule.StatusSPS"
      optional :state, :message, 8, "commonmodule.Optional_StateKind"
      optional :syncBackToGrid, :message, 9, "commonmodule.StatusSPS"
      optional :transToIslndOnGridLossEnabled, :message, 10, "commonmodule.StatusSPS"
      optional :voltageSetPointEnabled, :message, 11, "commonmodule.StatusSPS"
      optional :enterServiceOperation, :message, 12, "commonmodule.EnterServiceAPC"
      optional :hzWOperation, :message, 13, "commonmodule.HzWAPC"
      optional :limitWOperation, :message, 14, "commonmodule.LimitWAPC"
      optional :pFOperation, :message, 15, "commonmodule.PFSPC"
      optional :tmHzTripOperation, :message, 16, "commonmodule.TmHzCSG"
      optional :tmVoltTripOperation, :message, 17, "commonmodule.TmVoltCSG"
      optional :vArOperation, :message, 18, "commonmodule.VarSPC"
      optional :voltVarOperation, :message, 19, "commonmodule.VoltVarCSG"
      optional :voltWOperation, :message, 20, "commonmodule.VoltWCSG"
      optional :wVarOperation, :message, 21, "commonmodule.WVarCSG"
    end
    add_message "generationmodule.GenerationEventAndStatusZGEN" do
      optional :logicalNodeForEventAndStatus, :message, 1, "commonmodule.LogicalNodeForEventAndStatus"
      optional :AuxPwrSt, :message, 2, "commonmodule.StatusSPS"
      optional :DynamicTest, :message, 3, "commonmodule.ENS_DynamicTestKind"
      optional :EmgStop, :message, 4, "commonmodule.StatusSPS"
      optional :GnSynSt, :message, 5, "commonmodule.StatusSPS"
      optional :PointStatus, :message, 6, "generationmodule.GenerationPointStatus"
      optional :Alrm, :message, 7, "commonmodule.Optional_AlrmKind"
      optional :GridConnectionState, :message, 8, "commonmodule.Optional_GridConnectionStateKind"
      optional :ManAlrmInfo, :message, 9, "google.protobuf.StringValue"
      optional :OperatingState, :message, 10, "commonmodule.Optional_OperatingStateKind"
    end
    add_message "generationmodule.GenerationEventZGEN" do
      optional :generationEventAndStatusZGEN, :message, 1, "generationmodule.GenerationEventAndStatusZGEN"
    end
    add_message "generationmodule.GenerationEvent" do
      optional :eventValue, :message, 1, "commonmodule.EventValue"
      optional :generationEventZGEN, :message, 2, "generationmodule.GenerationEventZGEN"
    end
    add_message "generationmodule.GenerationEventProfile" do
      optional :eventMessageInfo, :message, 1, "commonmodule.EventMessageInfo"
      optional :generatingUnit, :message, 2, "generationmodule.GeneratingUnit"
      optional :generationEvent, :message, 3, "generationmodule.GenerationEvent"
    end
    add_message "generationmodule.GenerationStatusZGEN" do
      optional :generationEventAndStatusZGEN, :message, 1, "generationmodule.GenerationEventAndStatusZGEN"
    end
    add_message "generationmodule.GenerationStatus" do
      optional :statusValue, :message, 1, "commonmodule.StatusValue"
      optional :generationStatusZGEN, :message, 2, "generationmodule.GenerationStatusZGEN"
    end
    add_message "generationmodule.GenerationStatusProfile" do
      optional :statusMessageInfo, :message, 1, "commonmodule.StatusMessageInfo"
      optional :generatingUnit, :message, 2, "generationmodule.GeneratingUnit"
      optional :generationStatus, :message, 3, "generationmodule.GenerationStatus"
    end
  end
end

module Generationmodule
  GeneratingUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GeneratingUnit").msgclass
  GenerationCapabilityConfiguration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationCapabilityConfiguration").msgclass
  GenerationCapabilityOverride = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationCapabilityOverride").msgclass
  GenerationCapabilityOverrideProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationCapabilityOverrideProfile").msgclass
  GenerationCapabilityRatings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationCapabilityRatings").msgclass
  GenerationCapability = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationCapability").msgclass
  GenerationCapabilityProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationCapabilityProfile").msgclass
  GenerationPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationPoint").msgclass
  GenerationCSG = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationCSG").msgclass
  GenerationControlScheduleFSCH = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationControlScheduleFSCH").msgclass
  GenerationControlFSCC = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationControlFSCC").msgclass
  GenerationControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationControl").msgclass
  GenerationControlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationControlProfile").msgclass
  DroopParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.DroopParameter").msgclass
  RealPowerControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.RealPowerControl").msgclass
  ReactivePowerControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.ReactivePowerControl").msgclass
  GenerationDiscreteControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationDiscreteControl").msgclass
  GenerationDiscreteControlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationDiscreteControlProfile").msgclass
  GenerationReading = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationReading").msgclass
  GenerationReadingProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationReadingProfile").msgclass
  GenerationPointStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationPointStatus").msgclass
  GenerationEventAndStatusZGEN = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationEventAndStatusZGEN").msgclass
  GenerationEventZGEN = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationEventZGEN").msgclass
  GenerationEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationEvent").msgclass
  GenerationEventProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationEventProfile").msgclass
  GenerationStatusZGEN = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationStatusZGEN").msgclass
  GenerationStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationStatus").msgclass
  GenerationStatusProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generationmodule.GenerationStatusProfile").msgclass
end
