# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: switchmodule/switchmodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("switchmodule/switchmodule.proto", :syntax => :proto3) do
    add_message "switchmodule.SwitchDiscreteControlXSWI" do
      optional :logicalNodeForControl, :message, 1, "commonmodule.LogicalNodeForControl"
      optional :Pos, :message, 2, "commonmodule.PhaseDPC"
      optional :ResetProtectionPickup, :message, 3, "commonmodule.ControlSPC"
    end
    add_message "switchmodule.SwitchDiscreteControl" do
      optional :controlValue, :message, 1, "commonmodule.ControlValue"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      optional :switchDiscreteControlXSWI, :message, 3, "switchmodule.SwitchDiscreteControlXSWI"
    end
    add_message "switchmodule.ProtectedSwitch" do
      optional :conductingEquipment, :message, 1, "commonmodule.ConductingEquipment"
    end
    add_message "switchmodule.SwitchDiscreteControlProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :protectedSwitch, :message, 2, "switchmodule.ProtectedSwitch"
      optional :switchDiscreteControl, :message, 3, "switchmodule.SwitchDiscreteControl"
    end
    add_message "switchmodule.SwitchEventXSWI" do
      optional :logicalNodeForEventAndStatus, :message, 1, "commonmodule.LogicalNodeForEventAndStatus"
      optional :DynamicTest, :message, 2, "commonmodule.ENS_DynamicTestKind"
      optional :Pos, :message, 3, "commonmodule.PhaseDPS"
    end
    add_message "switchmodule.SwitchEvent" do
      optional :eventValue, :message, 1, "commonmodule.EventValue"
      optional :switchEventXSWI, :message, 2, "switchmodule.SwitchEventXSWI"
    end
    add_message "switchmodule.SwitchEventProfile" do
      optional :eventMessageInfo, :message, 1, "commonmodule.EventMessageInfo"
      optional :protectedSwitch, :message, 2, "switchmodule.ProtectedSwitch"
      optional :switchEvent, :message, 3, "switchmodule.SwitchEvent"
    end
    add_message "switchmodule.SwitchReading" do
      optional :conductingEquipmentTerminalReading, :message, 1, "commonmodule.ConductingEquipmentTerminalReading"
      optional :diffReadingMMXU, :message, 2, "commonmodule.ReadingMMXU"
      optional :phaseMMTN, :message, 3, "commonmodule.PhaseMMTN"
      optional :readingMMTR, :message, 4, "commonmodule.ReadingMMTR"
      optional :readingMMXU, :message, 5, "commonmodule.ReadingMMXU"
    end
    add_message "switchmodule.SwitchReadingProfile" do
      optional :readingMessageInfo, :message, 1, "commonmodule.ReadingMessageInfo"
      optional :protectedSwitch, :message, 2, "switchmodule.ProtectedSwitch"
      repeated :switchReading, :message, 3, "switchmodule.SwitchReading"
    end
    add_message "switchmodule.SwitchStatusXSWI" do
      optional :logicalNodeForEventAndStatus, :message, 1, "commonmodule.LogicalNodeForEventAndStatus"
      optional :DynamicTest, :message, 2, "commonmodule.ENS_DynamicTestKind"
      optional :Pos, :message, 4, "commonmodule.PhaseDPS"
      optional :ProtectionPickup, :message, 5, "commonmodule.PhaseSPS"
    end
    add_message "switchmodule.SwitchStatus" do
      optional :statusValue, :message, 1, "commonmodule.StatusValue"
      optional :switchStatusXSWI, :message, 2, "switchmodule.SwitchStatusXSWI"
    end
    add_message "switchmodule.SwitchStatusProfile" do
      optional :statusMessageInfo, :message, 1, "commonmodule.StatusMessageInfo"
      optional :protectedSwitch, :message, 2, "switchmodule.ProtectedSwitch"
      optional :switchStatus, :message, 3, "switchmodule.SwitchStatus"
    end
  end
end

module Switchmodule
  SwitchDiscreteControlXSWI = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchDiscreteControlXSWI").msgclass
  SwitchDiscreteControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchDiscreteControl").msgclass
  ProtectedSwitch = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.ProtectedSwitch").msgclass
  SwitchDiscreteControlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchDiscreteControlProfile").msgclass
  SwitchEventXSWI = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchEventXSWI").msgclass
  SwitchEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchEvent").msgclass
  SwitchEventProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchEventProfile").msgclass
  SwitchReading = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchReading").msgclass
  SwitchReadingProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchReadingProfile").msgclass
  SwitchStatusXSWI = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchStatusXSWI").msgclass
  SwitchStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchStatus").msgclass
  SwitchStatusProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("switchmodule.SwitchStatusProfile").msgclass
end
