# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uml.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'


descriptor_data = "\n\tuml.proto\x12\x03uml\x1a google/protobuf/descriptor.proto:>\n\x15option_parent_message\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\x08:>\n\x15option_required_field\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x08:@\n\x17option_multiplicity_min\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x05:@\n\x17option_multiplicity_max\x12\x1d.google.protobuf.FieldOptions\x18\xd3\x86\x03 \x01(\x05:4\n\x0boption_uuid\x12\x1d.google.protobuf.FieldOptions\x18\xd4\x86\x03 \x01(\x08:3\n\noption_key\x12\x1d.google.protobuf.FieldOptions\x18\xd5\x86\x03 \x01(\x08:A\n\x16option_openfmb_profile\x12\x1f.google.protobuf.MessageOptions\x18\xb8\x8e\x03 \x01(\x08\x42]\n\x07openfmbP\x01ZFgitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/v2/openfmb\xaa\x02\x07openfmbb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Uml
end
