# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uml.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("uml.proto", :syntax => :proto3) do
  end
end

module Uml
end
