# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loadmodule/loadmodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'google/protobuf/wrappers_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("loadmodule/loadmodule.proto", :syntax => :proto3) do
    add_message "loadmodule.LoadPoint" do
      optional :rampRates, :message, 1, "commonmodule.RampRate"
      optional :reactivePwrSetPointEnabled, :message, 2, "commonmodule.ControlSPC"
      optional :realPwrSetPointEnabled, :message, 3, "commonmodule.ControlSPC"
      optional :reset, :message, 4, "commonmodule.ControlSPC"
      optional :state, :message, 5, "commonmodule.Optional_StateKind"
      optional :startTime, :message, 6, "commonmodule.ControlTimestamp"
    end
    add_message "loadmodule.LoadCSG" do
      repeated :crvPts, :message, 1, "loadmodule.LoadPoint"
    end
    add_message "loadmodule.LoadControlScheduleFSCH" do
      optional :ValDCSG, :message, 1, "loadmodule.LoadCSG"
    end
    add_message "loadmodule.LoadControlFSCC" do
      optional :controlFSCC, :message, 1, "commonmodule.ControlFSCC"
      optional :loadControlScheduleFSCH, :message, 2, "loadmodule.LoadControlScheduleFSCH"
    end
    add_message "loadmodule.LoadControl" do
      optional :controlValue, :message, 1, "commonmodule.ControlValue"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      optional :loadControlFSCC, :message, 3, "loadmodule.LoadControlFSCC"
    end
    add_message "loadmodule.LoadControlProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :energyConsumer, :message, 2, "commonmodule.EnergyConsumer"
      optional :loadControl, :message, 3, "loadmodule.LoadControl"
    end
    add_message "loadmodule.LoadPointStatus" do
      optional :rampRates, :message, 1, "commonmodule.RampRate"
      optional :reactivePwrSetPointEnabled, :message, 2, "commonmodule.StatusSPS"
      optional :realPwrSetPointEnabled, :message, 3, "commonmodule.StatusSPS"
      optional :reset, :message, 4, "commonmodule.StatusSPS"
      optional :state, :message, 5, "commonmodule.Optional_StateKind"
    end
    add_message "loadmodule.LoadEventAndStatusZGLD" do
      optional :logicalNodeForEventAndStatus, :message, 1, "commonmodule.LogicalNodeForEventAndStatus"
      optional :DynamicTest, :message, 2, "commonmodule.ENS_DynamicTestKind"
      optional :EmgStop, :message, 3, "commonmodule.StatusSPS"
      optional :PointStatus, :message, 4, "loadmodule.LoadPointStatus"
    end
    add_message "loadmodule.LoadEventZGLD" do
      optional :loadEventAndStatusZGLD, :message, 1, "loadmodule.LoadEventAndStatusZGLD"
    end
    add_message "loadmodule.LoadEvent" do
      optional :eventValue, :message, 1, "commonmodule.EventValue"
      optional :loadEventZGLD, :message, 2, "loadmodule.LoadEventZGLD"
    end
    add_message "loadmodule.LoadEventProfile" do
      optional :eventMessageInfo, :message, 1, "commonmodule.EventMessageInfo"
      optional :energyConsumer, :message, 2, "commonmodule.EnergyConsumer"
      optional :loadEvent, :message, 3, "loadmodule.LoadEvent"
    end
    add_message "loadmodule.LoadReading" do
      optional :conductingEquipmentTerminalReading, :message, 1, "commonmodule.ConductingEquipmentTerminalReading"
      optional :phaseMMTN, :message, 2, "commonmodule.PhaseMMTN"
      optional :readingMMTR, :message, 3, "commonmodule.ReadingMMTR"
      optional :readingMMXU, :message, 4, "commonmodule.ReadingMMXU"
    end
    add_message "loadmodule.LoadReadingProfile" do
      optional :readingMessageInfo, :message, 1, "commonmodule.ReadingMessageInfo"
      optional :energyConsumer, :message, 2, "commonmodule.EnergyConsumer"
      optional :loadReading, :message, 3, "loadmodule.LoadReading"
    end
    add_message "loadmodule.LoadStatusZGLD" do
      optional :loadEventAndStatusZGLD, :message, 1, "loadmodule.LoadEventAndStatusZGLD"
    end
    add_message "loadmodule.LoadStatus" do
      optional :statusValue, :message, 1, "commonmodule.StatusValue"
      optional :isUncontrollable, :message, 2, "google.protobuf.BoolValue"
      optional :loadStatusZGLD, :message, 3, "loadmodule.LoadStatusZGLD"
    end
    add_message "loadmodule.LoadStatusProfile" do
      optional :statusMessageInfo, :message, 1, "commonmodule.StatusMessageInfo"
      optional :energyConsumer, :message, 2, "commonmodule.EnergyConsumer"
      optional :loadStatus, :message, 3, "loadmodule.LoadStatus"
    end
  end
end

module Loadmodule
  LoadPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadPoint").msgclass
  LoadCSG = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadCSG").msgclass
  LoadControlScheduleFSCH = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadControlScheduleFSCH").msgclass
  LoadControlFSCC = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadControlFSCC").msgclass
  LoadControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadControl").msgclass
  LoadControlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadControlProfile").msgclass
  LoadPointStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadPointStatus").msgclass
  LoadEventAndStatusZGLD = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadEventAndStatusZGLD").msgclass
  LoadEventZGLD = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadEventZGLD").msgclass
  LoadEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadEvent").msgclass
  LoadEventProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadEventProfile").msgclass
  LoadReading = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadReading").msgclass
  LoadReadingProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadReadingProfile").msgclass
  LoadStatusZGLD = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadStatusZGLD").msgclass
  LoadStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadStatus").msgclass
  LoadStatusProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("loadmodule.LoadStatusProfile").msgclass
end
