# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: circuitsegmentservicemodule/circuitsegmentservicemodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'google/protobuf/wrappers_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("circuitsegmentservicemodule/circuitsegmentservicemodule.proto", :syntax => :proto3) do
    add_message "circuitsegmentservicemodule.Optional_CircuitSegmentServiceModeKind" do
      optional :value, :enum, 1, "circuitsegmentservicemodule.CircuitSegmentServiceModeKind"
    end
    add_message "circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind" do
      optional :setVal, :enum, 1, "circuitsegmentservicemodule.CircuitSegmentServiceModeKind"
      optional :setValExtension, :message, 2, "google.protobuf.StringValue"
    end
    add_message "circuitsegmentservicemodule.CircuitSegmentControlDCSC" do
      optional :logicalNodeForControl, :message, 1, "commonmodule.LogicalNodeForControl"
      optional :CircuitSegmentServiceMode, :message, 2, "circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind"
      optional :Island, :message, 3, "commonmodule.ControlDPC"
    end
    add_message "circuitsegmentservicemodule.CircuitSegmentControl" do
      optional :identifiedObject, :message, 1, "commonmodule.IdentifiedObject"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      optional :circuitSegmentControlDCSC, :message, 3, "circuitsegmentservicemodule.CircuitSegmentControlDCSC"
    end
    add_message "circuitsegmentservicemodule.CircuitSegmentControlProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :applicationSystem, :message, 2, "commonmodule.ApplicationSystem"
      optional :circuitSegmentControl, :message, 3, "circuitsegmentservicemodule.CircuitSegmentControl"
    end
    add_message "circuitsegmentservicemodule.CircuitSegmentEventDCSC" do
      optional :logicalNode, :message, 1, "commonmodule.LogicalNode"
      optional :CircuitSegmentServiceMode, :message, 2, "circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind"
      optional :Island, :message, 3, "commonmodule.StatusSPS"
      optional :PermissibleAuto, :message, 4, "commonmodule.StatusSPS"
      optional :PermissibleManual, :message, 5, "commonmodule.StatusSPS"
      optional :PermissibleNetzero, :message, 6, "commonmodule.StatusSPS"
      optional :PermissibleStart, :message, 7, "commonmodule.StatusSPS"
      optional :PermissibleStop, :message, 8, "commonmodule.StatusSPS"
    end
    add_message "circuitsegmentservicemodule.CircuitSegmentEvent" do
      optional :identifiedObject, :message, 1, "commonmodule.IdentifiedObject"
      optional :circuitSegmentEventDCSC, :message, 2, "circuitsegmentservicemodule.CircuitSegmentEventDCSC"
    end
    add_message "circuitsegmentservicemodule.CircuitSegmentEventProfile" do
      optional :eventMessageInfo, :message, 1, "commonmodule.EventMessageInfo"
      optional :applicationSystem, :message, 2, "commonmodule.ApplicationSystem"
      optional :circuitSegmentEvent, :message, 3, "circuitsegmentservicemodule.CircuitSegmentEvent"
    end
    add_message "circuitsegmentservicemodule.CircuitSegmentStatusDCSC" do
      optional :logicalNode, :message, 1, "commonmodule.LogicalNode"
      optional :CircuitSegmentServiceMode, :message, 2, "circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind"
      optional :Island, :message, 3, "commonmodule.StatusDPS"
      optional :PermissibleAuto, :message, 4, "commonmodule.StatusSPS"
      optional :PermissibleManual, :message, 5, "commonmodule.StatusSPS"
      optional :PermissibleNetzero, :message, 6, "commonmodule.StatusSPS"
      optional :PermissibleStart, :message, 7, "commonmodule.StatusSPS"
      optional :PermissibleStop, :message, 8, "commonmodule.StatusSPS"
    end
    add_message "circuitsegmentservicemodule.CircuitSegmentStatus" do
      optional :identifiedObject, :message, 1, "commonmodule.IdentifiedObject"
      optional :circuitSegmentStatusDCSC, :message, 2, "circuitsegmentservicemodule.CircuitSegmentStatusDCSC"
    end
    add_message "circuitsegmentservicemodule.CircuitSegmentStatusProfile" do
      optional :statusMessageInfo, :message, 1, "commonmodule.StatusMessageInfo"
      optional :applicationSystem, :message, 2, "commonmodule.ApplicationSystem"
      optional :circuitSegmentStatus, :message, 3, "circuitsegmentservicemodule.CircuitSegmentStatus"
    end
    add_enum "circuitsegmentservicemodule.CircuitSegmentServiceModeKind" do
      value :CircuitSegmentServiceModeKind_UNDEFINED, 0
      value :CircuitSegmentServiceModeKind_none, 1
      value :CircuitSegmentServiceModeKind_auto, 2
      value :CircuitSegmentServiceModeKind_manual, 3
      value :CircuitSegmentServiceModeKind_netzero, 4
      value :CircuitSegmentServiceModeKind_start, 5
      value :CircuitSegmentServiceModeKind_stop, 6
    end
  end
end

module Circuitsegmentservicemodule
  Optional_CircuitSegmentServiceModeKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.Optional_CircuitSegmentServiceModeKind").msgclass
  ENG_CircuitSegmentServiceModeKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind").msgclass
  CircuitSegmentControlDCSC = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.CircuitSegmentControlDCSC").msgclass
  CircuitSegmentControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.CircuitSegmentControl").msgclass
  CircuitSegmentControlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.CircuitSegmentControlProfile").msgclass
  CircuitSegmentEventDCSC = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.CircuitSegmentEventDCSC").msgclass
  CircuitSegmentEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.CircuitSegmentEvent").msgclass
  CircuitSegmentEventProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.CircuitSegmentEventProfile").msgclass
  CircuitSegmentStatusDCSC = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.CircuitSegmentStatusDCSC").msgclass
  CircuitSegmentStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.CircuitSegmentStatus").msgclass
  CircuitSegmentStatusProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.CircuitSegmentStatusProfile").msgclass
  CircuitSegmentServiceModeKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("circuitsegmentservicemodule.CircuitSegmentServiceModeKind").enummodule
end
