# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interconnectionmodule/interconnectionmodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'google/protobuf/wrappers_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("interconnectionmodule/interconnectionmodule.proto", :syntax => :proto3) do
    add_message "interconnectionmodule.InterconnectionPoint" do
      optional :blackStartEnabled, :message, 1, "commonmodule.ControlSPC"
      optional :frequencySetPointEnabled, :message, 2, "commonmodule.ControlSPC"
      optional :island, :message, 3, "commonmodule.ControlSPC"
      optional :pctHzDroop, :message, 4, "google.protobuf.FloatValue"
      optional :pctVDroop, :message, 5, "google.protobuf.FloatValue"
      optional :rampRates, :message, 6, "commonmodule.RampRate"
      optional :reactivePwrSetPointEnabled, :message, 7, "commonmodule.ControlSPC"
      optional :realPwrSetPointEnabled, :message, 8, "commonmodule.ControlSPC"
      optional :voltageSetPointEnabled, :message, 9, "commonmodule.ControlSPC"
      optional :startTime, :message, 10, "commonmodule.Timestamp"
    end
    add_message "interconnectionmodule.InterconnectionCSG" do
      repeated :crvPts, :message, 1, "interconnectionmodule.InterconnectionPoint"
    end
    add_message "interconnectionmodule.InterconnectionControlScheduleFSCH" do
      optional :ValDCSG, :message, 1, "interconnectionmodule.InterconnectionCSG"
    end
    add_message "interconnectionmodule.InterconnectionScheduleFSCC" do
      optional :controlFSCC, :message, 1, "commonmodule.ControlFSCC"
      repeated :interconnectionControlScheduleFSCH, :message, 2, "interconnectionmodule.InterconnectionControlScheduleFSCH"
    end
    add_message "interconnectionmodule.InterconnectionSchedule" do
      optional :identifiedObject, :message, 1, "commonmodule.IdentifiedObject"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      optional :interconnectionScheduleFSCC, :message, 3, "interconnectionmodule.InterconnectionScheduleFSCC"
    end
    add_message "interconnectionmodule.InterconnectionPlannedScheduleProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :requesterCircuitSegmentService, :message, 2, "commonmodule.ApplicationSystem"
      optional :interconnectionSchedule, :message, 3, "interconnectionmodule.InterconnectionSchedule"
      optional :tiePoint, :message, 4, "commonmodule.ConductingEquipment"
      optional :responderCircuitSegmentService, :message, 5, "commonmodule.ApplicationSystem"
    end
    add_message "interconnectionmodule.InterconnectionRequestedScheduleProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :requesterCircuitSegmentService, :message, 2, "commonmodule.ApplicationSystem"
      optional :interconnectionSchedule, :message, 3, "interconnectionmodule.InterconnectionSchedule"
      optional :tiePoint, :message, 4, "commonmodule.ConductingEquipment"
      optional :responderCircuitSegmentService, :message, 5, "commonmodule.ApplicationSystem"
    end
  end
end

module Interconnectionmodule
  InterconnectionPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interconnectionmodule.InterconnectionPoint").msgclass
  InterconnectionCSG = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interconnectionmodule.InterconnectionCSG").msgclass
  InterconnectionControlScheduleFSCH = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interconnectionmodule.InterconnectionControlScheduleFSCH").msgclass
  InterconnectionScheduleFSCC = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interconnectionmodule.InterconnectionScheduleFSCC").msgclass
  InterconnectionSchedule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interconnectionmodule.InterconnectionSchedule").msgclass
  InterconnectionPlannedScheduleProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interconnectionmodule.InterconnectionPlannedScheduleProfile").msgclass
  InterconnectionRequestedScheduleProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interconnectionmodule.InterconnectionRequestedScheduleProfile").msgclass
end
