# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capbankmodule/capbankmodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("capbankmodule/capbankmodule.proto", :syntax => :proto3) do
    add_message "capbankmodule.CapBankSystem" do
      optional :conductingEquipment, :message, 1, "commonmodule.ConductingEquipment"
    end
    add_message "capbankmodule.CapBankControlYPSH" do
      optional :AmpLmt, :message, 1, "commonmodule.PhaseSPC"
      optional :AmpThdHi, :message, 2, "commonmodule.PhaseAPC"
      optional :AmpThdLo, :message, 3, "commonmodule.PhaseAPC"
      optional :CtlModeAuto, :message, 4, "commonmodule.ControlSPC"
      optional :CtlModeOvrRd, :message, 5, "commonmodule.ControlSPC"
      optional :CtlModeRem, :message, 6, "commonmodule.ControlSPC"
      optional :DirMode, :message, 7, "commonmodule.Optional_DirectionModeKind"
      optional :Pos, :message, 8, "commonmodule.PhaseSPC"
      optional :TempLmt, :message, 9, "commonmodule.ControlSPC"
      optional :TempThdHi, :message, 10, "commonmodule.ControlAPC"
      optional :TempThdLo, :message, 11, "commonmodule.ControlAPC"
      optional :VArLmt, :message, 12, "commonmodule.PhaseSPC"
      optional :VArThdHi, :message, 13, "commonmodule.PhaseAPC"
      optional :VArThdLo, :message, 14, "commonmodule.PhaseAPC"
      optional :VolLmt, :message, 15, "commonmodule.PhaseSPC"
      optional :VolThdHi, :message, 16, "commonmodule.PhaseAPC"
      optional :VolThdLo, :message, 17, "commonmodule.PhaseAPC"
    end
    add_message "capbankmodule.CapBankPoint" do
      optional :control, :message, 1, "capbankmodule.CapBankControlYPSH"
      optional :startTime, :message, 2, "commonmodule.Timestamp"
    end
    add_message "capbankmodule.CapBankCSG" do
      repeated :crvPts, :message, 1, "capbankmodule.CapBankPoint"
    end
    add_message "capbankmodule.CapBankControlScheduleFSCH" do
      optional :ValCSG, :message, 1, "capbankmodule.CapBankCSG"
    end
    add_message "capbankmodule.CapBankControlFSCC" do
      optional :controlFSCC, :message, 1, "commonmodule.ControlFSCC"
      optional :capBankControlScheduleFSCH, :message, 2, "capbankmodule.CapBankControlScheduleFSCH"
    end
    add_message "capbankmodule.CapBankControl" do
      optional :controlValue, :message, 1, "commonmodule.ControlValue"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      optional :capBankControlFSCC, :message, 3, "capbankmodule.CapBankControlFSCC"
    end
    add_message "capbankmodule.CapBankControlProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :capBankControl, :message, 2, "capbankmodule.CapBankControl"
      optional :capBankSystem, :message, 3, "capbankmodule.CapBankSystem"
    end
    add_message "capbankmodule.CapBankDiscreteControlYPSH" do
      optional :logicalNodeForControl, :message, 1, "commonmodule.LogicalNodeForControl"
      optional :control, :message, 2, "capbankmodule.CapBankControlYPSH"
    end
    add_message "capbankmodule.CapBankDiscreteControl" do
      optional :controlValue, :message, 1, "commonmodule.ControlValue"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      optional :capBankDiscreteControlYPSH, :message, 3, "capbankmodule.CapBankDiscreteControlYPSH"
    end
    add_message "capbankmodule.CapBankDiscreteControlProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :capBankControl, :message, 2, "capbankmodule.CapBankDiscreteControl"
      optional :capBankSystem, :message, 3, "capbankmodule.CapBankSystem"
    end
    add_message "capbankmodule.CapBankEventAndStatusYPSH" do
      optional :logicalNodeForEventAndStatus, :message, 1, "commonmodule.LogicalNodeForEventAndStatus"
      optional :AmpLmt, :message, 2, "commonmodule.PhaseSPS"
      optional :CtlMode, :message, 3, "commonmodule.Optional_ControlModeKind"
      optional :DirRev, :message, 4, "commonmodule.PhaseSPS"
      optional :DynamicTest, :message, 5, "commonmodule.ENS_DynamicTestKind"
      optional :Pos, :message, 6, "commonmodule.PhaseDPS"
      optional :TempLmt, :message, 7, "commonmodule.PhaseSPS"
      optional :VArLmt, :message, 8, "commonmodule.PhaseSPS"
      optional :VolLmt, :message, 9, "commonmodule.PhaseSPS"
    end
    add_message "capbankmodule.CapBankEvent" do
      optional :eventValue, :message, 1, "commonmodule.EventValue"
      optional :CapBankEventAndStatusYPSH, :message, 2, "capbankmodule.CapBankEventAndStatusYPSH"
    end
    add_message "capbankmodule.CapBankEventProfile" do
      optional :eventMessageInfo, :message, 1, "commonmodule.EventMessageInfo"
      optional :capBankEvent, :message, 2, "capbankmodule.CapBankEvent"
      optional :capBankSystem, :message, 3, "capbankmodule.CapBankSystem"
    end
    add_message "capbankmodule.CapBankReading" do
      optional :conductingEquipmentTerminalReading, :message, 1, "commonmodule.ConductingEquipmentTerminalReading"
      optional :phaseMMTN, :message, 2, "commonmodule.PhaseMMTN"
      optional :readingMMTR, :message, 3, "commonmodule.ReadingMMTR"
      optional :readingMMXU, :message, 4, "commonmodule.ReadingMMXU"
      optional :secondaryReadingMMXU, :message, 5, "commonmodule.ReadingMMXU"
    end
    add_message "capbankmodule.CapBankReadingProfile" do
      optional :readingMessageInfo, :message, 1, "commonmodule.ReadingMessageInfo"
      optional :capBankReading, :message, 2, "capbankmodule.CapBankReading"
      optional :capBankSystem, :message, 3, "capbankmodule.CapBankSystem"
    end
    add_message "capbankmodule.CapBankStatus" do
      optional :statusValue, :message, 1, "commonmodule.StatusValue"
      optional :capBankEventAndStatusYPSH, :message, 2, "capbankmodule.CapBankEventAndStatusYPSH"
    end
    add_message "capbankmodule.CapBankStatusProfile" do
      optional :statusMessageInfo, :message, 1, "commonmodule.StatusMessageInfo"
      optional :capBankStatus, :message, 2, "capbankmodule.CapBankStatus"
      optional :capBankSystem, :message, 3, "capbankmodule.CapBankSystem"
    end
  end
end

module Capbankmodule
  CapBankSystem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankSystem").msgclass
  CapBankControlYPSH = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankControlYPSH").msgclass
  CapBankPoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankPoint").msgclass
  CapBankCSG = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankCSG").msgclass
  CapBankControlScheduleFSCH = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankControlScheduleFSCH").msgclass
  CapBankControlFSCC = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankControlFSCC").msgclass
  CapBankControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankControl").msgclass
  CapBankControlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankControlProfile").msgclass
  CapBankDiscreteControlYPSH = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankDiscreteControlYPSH").msgclass
  CapBankDiscreteControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankDiscreteControl").msgclass
  CapBankDiscreteControlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankDiscreteControlProfile").msgclass
  CapBankEventAndStatusYPSH = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankEventAndStatusYPSH").msgclass
  CapBankEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankEvent").msgclass
  CapBankEventProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankEventProfile").msgclass
  CapBankReading = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankReading").msgclass
  CapBankReadingProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankReadingProfile").msgclass
  CapBankStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankStatus").msgclass
  CapBankStatusProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("capbankmodule.CapBankStatusProfile").msgclass
end
