# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reservemodule/reservemodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("reservemodule/reservemodule.proto", :syntax => :proto3) do
    add_message "reservemodule.ReserveMargin" do
      optional :logicalNode, :message, 1, "commonmodule.LogicalNode"
      optional :A, :message, 2, "commonmodule.PMG"
      optional :VA, :message, 3, "commonmodule.PMG"
      optional :VAr, :message, 4, "commonmodule.PMG"
      optional :W, :message, 5, "commonmodule.PMG"
    end
    add_message "reservemodule.ReserveAvailability" do
      optional :incrementalMargin, :message, 1, "reservemodule.ReserveMargin"
      optional :margin, :message, 2, "reservemodule.ReserveMargin"
      optional :standbyMargin, :message, 3, "reservemodule.ReserveMargin"
    end
    add_message "reservemodule.AllocatedMargin" do
      optional :requestID, :string, 1
      optional :allocatedMargin, :message, 2, "reservemodule.ReserveMargin"
      optional :allocatedStandbyMargin, :message, 3, "reservemodule.ReserveMargin"
    end
    add_message "reservemodule.ReserveAvailabilityProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :allocatedMargin, :message, 2, "reservemodule.AllocatedMargin"
      optional :requesterCircuitSegmentService, :message, 3, "commonmodule.ApplicationSystem"
      optional :reserveAvailability, :message, 4, "reservemodule.ReserveAvailability"
      optional :responderCircuitSegmentService, :message, 5, "commonmodule.ApplicationSystem"
      optional :tiePoint, :message, 6, "commonmodule.ConductingEquipment"
    end
    add_message "reservemodule.ReserveRequest" do
      optional :requestID, :string, 1
      optional :margin, :message, 2, "reservemodule.ReserveMargin"
      optional :standbyMargin, :message, 3, "reservemodule.ReserveMargin"
    end
    add_message "reservemodule.ReserveRequestProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :requesterCircuitSegmentService, :message, 2, "commonmodule.ApplicationSystem"
      optional :reserveRequest, :message, 3, "reservemodule.ReserveRequest"
      optional :responderCircuitSegmentService, :message, 4, "commonmodule.ApplicationSystem"
      optional :tiePoint, :message, 5, "commonmodule.ConductingEquipment"
    end
  end
end

module Reservemodule
  ReserveMargin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reservemodule.ReserveMargin").msgclass
  ReserveAvailability = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reservemodule.ReserveAvailability").msgclass
  AllocatedMargin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reservemodule.AllocatedMargin").msgclass
  ReserveAvailabilityProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reservemodule.ReserveAvailabilityProfile").msgclass
  ReserveRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reservemodule.ReserveRequest").msgclass
  ReserveRequestProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reservemodule.ReserveRequestProfile").msgclass
end
