# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: breakermodule/breakermodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("breakermodule/breakermodule.proto", :syntax => :proto3) do
    add_message "breakermodule.BreakerDiscreteControlXCBR" do
      optional :discreteControlXCBR, :message, 1, "commonmodule.DiscreteControlXCBR"
    end
    add_message "breakermodule.BreakerDiscreteControl" do
      optional :controlValue, :message, 1, "commonmodule.ControlValue"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      optional :breakerDiscreteControlXCBR, :message, 3, "breakermodule.BreakerDiscreteControlXCBR"
    end
    add_message "breakermodule.Breaker" do
      optional :conductingEquipment, :message, 1, "commonmodule.ConductingEquipment"
    end
    add_message "breakermodule.BreakerDiscreteControlProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :breaker, :message, 2, "breakermodule.Breaker"
      optional :breakerDiscreteControl, :message, 3, "breakermodule.BreakerDiscreteControl"
    end
    add_message "breakermodule.BreakerEvent" do
      optional :eventValue, :message, 1, "commonmodule.EventValue"
      optional :statusAndEventXCBR, :message, 2, "commonmodule.StatusAndEventXCBR"
    end
    add_message "breakermodule.BreakerEventProfile" do
      optional :eventMessageInfo, :message, 1, "commonmodule.EventMessageInfo"
      optional :breaker, :message, 2, "breakermodule.Breaker"
      optional :breakerEvent, :message, 3, "breakermodule.BreakerEvent"
    end
    add_message "breakermodule.BreakerReading" do
      optional :conductingEquipmentTerminalReading, :message, 1, "commonmodule.ConductingEquipmentTerminalReading"
      optional :diffReadingMMXU, :message, 2, "commonmodule.ReadingMMXU"
      optional :phaseMMTN, :message, 3, "commonmodule.PhaseMMTN"
      optional :readingMMTR, :message, 4, "commonmodule.ReadingMMTR"
      optional :readingMMXU, :message, 5, "commonmodule.ReadingMMXU"
    end
    add_message "breakermodule.BreakerReadingProfile" do
      optional :readingMessageInfo, :message, 1, "commonmodule.ReadingMessageInfo"
      optional :breaker, :message, 2, "breakermodule.Breaker"
      repeated :breakerReading, :message, 3, "breakermodule.BreakerReading"
    end
    add_message "breakermodule.BreakerStatus" do
      optional :statusValue, :message, 1, "commonmodule.StatusValue"
      optional :statusAndEventXCBR, :message, 2, "commonmodule.StatusAndEventXCBR"
    end
    add_message "breakermodule.BreakerStatusProfile" do
      optional :statusMessageInfo, :message, 1, "commonmodule.StatusMessageInfo"
      optional :breaker, :message, 2, "breakermodule.Breaker"
      optional :breakerStatus, :message, 3, "breakermodule.BreakerStatus"
    end
  end
end

module Breakermodule
  BreakerDiscreteControlXCBR = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("breakermodule.BreakerDiscreteControlXCBR").msgclass
  BreakerDiscreteControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("breakermodule.BreakerDiscreteControl").msgclass
  Breaker = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("breakermodule.Breaker").msgclass
  BreakerDiscreteControlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("breakermodule.BreakerDiscreteControlProfile").msgclass
  BreakerEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("breakermodule.BreakerEvent").msgclass
  BreakerEventProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("breakermodule.BreakerEventProfile").msgclass
  BreakerReading = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("breakermodule.BreakerReading").msgclass
  BreakerReadingProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("breakermodule.BreakerReadingProfile").msgclass
  BreakerStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("breakermodule.BreakerStatus").msgclass
  BreakerStatusProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("breakermodule.BreakerStatusProfile").msgclass
end
