# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: environmentmodule/environmentmodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'commonmodule/commonmodule_pb'


descriptor_data = "\n)environmentmodule/environmentmodule.proto\x12\x11\x65nvironmentmodule\x1a\tuml.proto\x1a\x1f\x63ommonmodule/commonmodule.proto\"\xd8\x01\n\x12\x45nvironmentReading\x12\x62\n\"conductingEquipmentTerminalReading\x18\x01 \x01(\x0b\x32\x30.commonmodule.ConductingEquipmentTerminalReadingB\x04\x80\xb5\x18\x01\x12.\n\x0breadingMENV\x18\x02 \x01(\x0b\x32\x19.commonmodule.ReadingMENV\x12.\n\x0breadingMMET\x18\x03 \x01(\x0b\x32\x19.commonmodule.ReadingMMET\"\xe2\x01\n\x19\x45nvironmentReadingProfile\x12\x42\n\x12readingMessageInfo\x18\x01 \x01(\x0b\x32 .commonmodule.ReadingMessageInfoB\x04\x80\xb5\x18\x01\x12.\n\x06sensor\x18\x02 \x01(\x0b\x32\x14.commonmodule.SensorB\x08\x88\xb5\x18\x01\x90\xb5\x18\x01\x12K\n\x12\x65nvironmentReading\x18\x03 \x01(\x0b\x32%.environmentmodule.EnvironmentReadingB\x08\x88\xb5\x18\x01\x90\xb5\x18\x01:\x04\xc0\xf3\x18\x01\x42\x93\x01\n\x19openfmb.environmentmoduleP\x01ZXgitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/v2/openfmb/environmentmodule\xaa\x02\x19openfmb.environmentmoduleb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Environmentmodule
  EnvironmentReading = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("environmentmodule.EnvironmentReading").msgclass
  EnvironmentReadingProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("environmentmodule.EnvironmentReadingProfile").msgclass
end
