# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metermodule/metermodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'commonmodule/commonmodule_pb'


descriptor_data = "\n\x1dmetermodule/metermodule.proto\x12\x0bmetermodule\x1a\tuml.proto\x1a\x1f\x63ommonmodule/commonmodule.proto\"\xae\x02\n\x0cMeterReading\x12\x62\n\"conductingEquipmentTerminalReading\x18\x01 \x01(\x0b\x32\x30.commonmodule.ConductingEquipmentTerminalReadingB\x04\x80\xb5\x18\x01\x12*\n\tphaseMMTN\x18\x02 \x01(\x0b\x32\x17.commonmodule.PhaseMMTN\x12.\n\x0breadingMMTR\x18\x03 \x01(\x0b\x32\x19.commonmodule.ReadingMMTR\x12.\n\x0breadingMMXU\x18\x04 \x01(\x0b\x32\x19.commonmodule.ReadingMMXU\x12.\n\x0breadingMMDC\x18\x05 \x01(\x0b\x32\x19.commonmodule.ReadingMMDC\"\xc8\x01\n\x13MeterReadingProfile\x12\x42\n\x12readingMessageInfo\x18\x01 \x01(\x0b\x32 .commonmodule.ReadingMessageInfoB\x04\x80\xb5\x18\x01\x12,\n\x05meter\x18\x02 \x01(\x0b\x32\x13.commonmodule.MeterB\x08\x88\xb5\x18\x01\x90\xb5\x18\x01\x12\x39\n\x0cmeterReading\x18\x03 \x01(\x0b\x32\x19.metermodule.MeterReadingB\x08\x88\xb5\x18\x01\x90\xb5\x18\x01:\x04\xc0\xf3\x18\x01\x42\x81\x01\n\x13openfmb.metermoduleP\x01ZRgitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/v2/openfmb/metermodule\xaa\x02\x13openfmb.metermoduleb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Metermodule
  MeterReading = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("metermodule.MeterReading").msgclass
  MeterReadingProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("metermodule.MeterReadingProfile").msgclass
end
