# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metermodule/metermodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("metermodule/metermodule.proto", :syntax => :proto3) do
    add_message "metermodule.MeterReading" do
      optional :conductingEquipmentTerminalReading, :message, 1, "commonmodule.ConductingEquipmentTerminalReading"
      optional :phaseMMTN, :message, 2, "commonmodule.PhaseMMTN"
      optional :readingMMTR, :message, 3, "commonmodule.ReadingMMTR"
      optional :readingMMXU, :message, 4, "commonmodule.ReadingMMXU"
    end
    add_message "metermodule.MeterReadingProfile" do
      optional :readingMessageInfo, :message, 1, "commonmodule.ReadingMessageInfo"
      optional :meter, :message, 2, "commonmodule.Meter"
      optional :meterReading, :message, 3, "metermodule.MeterReading"
    end
  end
end

module Metermodule
  MeterReading = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("metermodule.MeterReading").msgclass
  MeterReadingProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("metermodule.MeterReadingProfile").msgclass
end
