# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reclosermodule/reclosermodule.proto

require 'google/protobuf'

require 'uml_pb'
require 'google/protobuf/wrappers_pb'
require 'commonmodule/commonmodule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("reclosermodule/reclosermodule.proto", :syntax => :proto3) do
    add_message "reclosermodule.RecloserDiscreteControlXCBR" do
      optional :discreteControlXCBR, :message, 1, "commonmodule.DiscreteControlXCBR"
    end
    add_message "reclosermodule.RecloserDiscreteControl" do
      optional :controlValue, :message, 1, "commonmodule.ControlValue"
      optional :check, :message, 2, "commonmodule.CheckConditions"
      optional :recloserDiscreteControlXCBR, :message, 3, "reclosermodule.RecloserDiscreteControlXCBR"
    end
    add_message "reclosermodule.Recloser" do
      optional :conductingEquipment, :message, 1, "commonmodule.ConductingEquipment"
      optional :normalOpen, :message, 2, "google.protobuf.BoolValue"
    end
    add_message "reclosermodule.RecloserDiscreteControlProfile" do
      optional :controlMessageInfo, :message, 1, "commonmodule.ControlMessageInfo"
      optional :recloser, :message, 2, "reclosermodule.Recloser"
      optional :recloserDiscreteControl, :message, 3, "reclosermodule.RecloserDiscreteControl"
    end
    add_message "reclosermodule.RecloserEvent" do
      optional :eventValue, :message, 1, "commonmodule.EventValue"
      optional :statusAndEventXCBR, :message, 2, "commonmodule.StatusAndEventXCBR"
    end
    add_message "reclosermodule.RecloserEventProfile" do
      optional :eventMessageInfo, :message, 1, "commonmodule.EventMessageInfo"
      optional :recloser, :message, 2, "reclosermodule.Recloser"
      optional :recloserEvent, :message, 3, "reclosermodule.RecloserEvent"
    end
    add_message "reclosermodule.RecloserReading" do
      optional :conductingEquipmentTerminalReading, :message, 1, "commonmodule.ConductingEquipmentTerminalReading"
      optional :diffReadingMMXU, :message, 2, "commonmodule.ReadingMMXU"
      optional :phaseMMTN, :message, 3, "commonmodule.PhaseMMTN"
      optional :readingMMTR, :message, 4, "commonmodule.ReadingMMTR"
      optional :readingMMXU, :message, 5, "commonmodule.ReadingMMXU"
    end
    add_message "reclosermodule.RecloserReadingProfile" do
      optional :readingMessageInfo, :message, 1, "commonmodule.ReadingMessageInfo"
      optional :recloser, :message, 2, "reclosermodule.Recloser"
      repeated :recloserReading, :message, 3, "reclosermodule.RecloserReading"
    end
    add_message "reclosermodule.RecloserStatus" do
      optional :statusValue, :message, 1, "commonmodule.StatusValue"
      optional :statusAndEventXCBR, :message, 2, "commonmodule.StatusAndEventXCBR"
    end
    add_message "reclosermodule.RecloserStatusProfile" do
      optional :statusMessageInfo, :message, 1, "commonmodule.StatusMessageInfo"
      optional :recloser, :message, 2, "reclosermodule.Recloser"
      optional :recloserStatus, :message, 3, "reclosermodule.RecloserStatus"
    end
  end
end

module Reclosermodule
  RecloserDiscreteControlXCBR = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reclosermodule.RecloserDiscreteControlXCBR").msgclass
  RecloserDiscreteControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reclosermodule.RecloserDiscreteControl").msgclass
  Recloser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reclosermodule.Recloser").msgclass
  RecloserDiscreteControlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reclosermodule.RecloserDiscreteControlProfile").msgclass
  RecloserEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reclosermodule.RecloserEvent").msgclass
  RecloserEventProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reclosermodule.RecloserEventProfile").msgclass
  RecloserReading = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reclosermodule.RecloserReading").msgclass
  RecloserReadingProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reclosermodule.RecloserReadingProfile").msgclass
  RecloserStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reclosermodule.RecloserStatus").msgclass
  RecloserStatusProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reclosermodule.RecloserStatusProfile").msgclass
end
